const app=document.getElementById('app');

const VERIFIED_SOURCES={
  centralRTI:{title:'RTI Online — Government of India',org:'Department of Personnel & Training',domain:'rtionline.gov.in',url:'https://rtionline.gov.in/',level:'CENTRAL'},
  indiaBudget:{title:'Union Budget — Government of India',org:'Ministry of Finance',domain:'indiabudget.gov.in',url:'https://www.indiabudget.gov.in/',level:'CENTRAL'},
  rail:{title:'Indian Railways',org:'Ministry of Railways',domain:'indianrailways.gov.in',url:'https://indianrailways.gov.in/',level:'CENTRAL'},
  data:{title:'Open Government Data Platform India',org:'Government of India',domain:'data.gov.in',url:'https://www.data.gov.in/',level:'CENTRAL'},
  mahaRTI:{title:'Maharashtra RTI Online',org:'General Administration Department, Government of Maharashtra',domain:'rtionline.maharashtra.gov.in',url:'https://rtionline.maharashtra.gov.in/',level:'STATE'},
  arunachal:{title:'Arunachal Pradesh State Portal',org:'Government of Arunachal Pradesh',domain:'arunachalpradesh.gov.in',url:'https://arunachalpradesh.gov.in/',level:'STATE'},
  arunachalRTI:{title:'Right to Information — Arunachal Pradesh',org:'Department of Planning, Investment & Finance, Government of Arunachal Pradesh',domain:'arunachalplan.gov.in',url:'https://arunachalplan.gov.in/rti/',level:'STATE'}
};

const RAIL_DEMO=[
  {year:'2021-22',value:117231.73,label:'Actual capital outlay — commercial lines'},
  {year:'2022-23',value:158997.06,label:'Revised estimate — commercial lines'},
  {year:'2023-24',value:239898.58,label:'Revised estimate — commercial lines'},
  {year:'2024-25',value:251893.08,label:'Budget estimate — commercial lines'}
];

const SAMPLE_RTIS=[
  {id:'JNK/2026/001284',title:'Railway station redevelopment expenditure',authority:'Ministry of Railways',jurisdiction:'CENTRAL',status:'RESPONSE_RECEIVED',date:'12 Aug 2026',hasDocument:true,docType:'response'},
  {id:'JNK/2026/001317',title:'Maharashtra district road maintenance records',authority:'Public Works Department, Government of Maharashtra',jurisdiction:'STATE',status:'UNDER_PROCESS',date:'16 Aug 2026',hasDocument:false},
  {id:'JNK/2026/001329',title:'Municipal ward road repair expenditure',authority:'Relevant Municipal Corporation',jurisdiction:'LOCAL',status:'TRANSFERRED',date:'17 Aug 2026',hasDocument:false},
  {id:'JNK/2026/001346',title:'Government school infrastructure grants',authority:'State Education Department',jurisdiction:'STATE',status:'PARTIALLY_ANSWERED',date:'19 Aug 2026',hasDocument:true,docType:'partial'},
  {id:'JNK/2026/001361',title:'Public hospital equipment procurement',authority:'State Health Department',jurisdiction:'STATE',status:'ADDITIONAL_INFO_REQUESTED',date:'21 Aug 2026',hasDocument:false},
  {id:'JNK/2026/001390',title:'Public works project expenditure',authority:'Public Works Department',jurisdiction:'STATE',status:'APPEAL_AVAILABLE',date:'24 Aug 2026',hasDocument:true,docType:'partial'}
];

let s={page:'landing',authed:false,user:null,userLoc:'',subjectLoc:'',query:'',result:null,draft:'',authority:'',jurisdiction:'',submission:null,response:null,selectedRti:null,docMode:null};
const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function brand(){return `<div class="brand" onclick="s.page='landing';render()"><img src="${LOGO_DATA}" alt="Jankar India logo"><div><b>JANKAR <span>INDIA</span></b><small>जानकारी आपका अधिकार</small></div></div>`}
function userMenu(){return s.authed?`<div class="user-menu"><button class="user-btn" onclick="toggleUserMenu()"><span class="avatar">T</span><span>Tasmayee</span>⌄</button><div id="userDrop" class="user-drop hidden"><button onclick="s.page='profile';render()">Profile</button><button onclick="logout()">Logout</button></div></div>`:`<button class="link-btn" onclick="login()">Login</button>`}
function shell(body,active=''){
  const nav=`<button class="${active==='Ask Jankar'?'active':''}" onclick="s.page='ask';render()">Ask Jankar</button><button class="${active==='My RTIs'?'active':''}" onclick="openMyRtis()">My RTIs</button><button class="${active==='Know About RTI'?'active':''}" onclick="s.page='guide';render()">Know About RTI</button>`;
  return `<header>${brand()}<nav>${nav}</nav>${userMenu()}</header>${body}<footer><div><b>Jankar India</b><p>Citizens shouldn't need to understand government machinery to get information from it.</p></div><div class="footer-trust"><span>Government sources only</span><span>Nothing submitted automatically</span><span>Location stays under your control</span></div></footer>`;
}
function toggleUserMenu(){document.getElementById('userDrop')?.classList.toggle('hidden')}
function login(){s.page='login';render()}
function logout(){s.authed=false;s.user=null;s.page='landing';s.selectedRti=null;render()}
function requireLogin(next){if(s.authed){s.page=next;render();return true}s.page='login';s.afterLogin=next;render();return false}
function openMyRtis(){requireLogin('track')}

function extractSubjectLocation(q){
  const t=q.toLowerCase();
  const states=['arunachal pradesh','maharashtra','rajasthan','karnataka','kerala','tamil nadu','gujarat','goa','assam','bihar','uttar pradesh','madhya pradesh','west bengal','odisha','punjab','haryana','telangana','andhra pradesh','jharkhand','chhattisgarh','uttarakhand','himachal pradesh','meghalaya','manipur','mizoram','nagaland','sikkim','tripura'];
  const found=states.find(x=>t.includes(x)); if(found)return found.replace(/\b\w/g,m=>m.toUpperCase());
  if(/\bpune\b/.test(t))return 'Pune, Maharashtra'; if(/\bmumbai\b/.test(t))return 'Mumbai, Maharashtra'; if(/\bjaipur\b/.test(t))return 'Jaipur, Rajasthan'; if(/\bitanagar\b/.test(t))return 'Itanagar, Arunachal Pradesh';
  return '';
}

function routeQuery(q,subjectLoc=''){
  const t=(q+' '+subjectLoc).toLowerCase();
  if(/railway|indian railways|income tax|passport|central university|union ministry|national highway authority/.test(t)){
    let authority='Relevant Central Government Public Authority';
    if(/railway/.test(t)) authority='Ministry of Railways';
    if(/income tax/.test(t)) authority='Income Tax Department';
    if(/passport/.test(t)) authority='Ministry of External Affairs';
    return {jurisdiction:'CENTRAL',authority,reason:`Jankar matched the subject to ${authority}, which is handled at the Central Government level.`,confidence:'High',state:null,routeUrl:VERIFIED_SOURCES.centralRTI.url,routeLabel:'Central RTI Online'};
  }
  if(/municipal corporation|municipality|panchayat|ward office|local body/.test(t)) return {jurisdiction:'LOCAL',authority:'Relevant Local Public Authority',reason:'The requested records appear to be maintained by a local public body.',confidence:'Medium',state:subjectLoc||null,routeUrl:null,routeLabel:null};
  if(/arunachal pradesh|itanagar/.test(t)) return {jurisdiction:'STATE',authority:'Relevant Government of Arunachal Pradesh Public Authority',reason:'The subject concerns records of the Government of Arunachal Pradesh.',confidence:'High',state:'Arunachal Pradesh',routeUrl:VERIFIED_SOURCES.arunachalRTI.url,routeLabel:'Official Arunachal Pradesh RTI information'};
  if(/maharashtra|\bpune\b|\bmumbai\b|nashik|kolhapur|state road|state education|state health|public works department/.test(t)) return {jurisdiction:'STATE',authority:'Relevant Government of Maharashtra Public Authority',reason:'The subject appears to concern records maintained by a Maharashtra State Government authority.',confidence:'High',state:'Maharashtra',routeUrl:VERIFIED_SOURCES.mahaRTI.url,routeLabel:'Maharashtra RTI Online'};
  const stateOnly=extractSubjectLocation(t);
  if(stateOnly) return {jurisdiction:'STATE',authority:`Relevant ${stateOnly} State Public Authority`,reason:`The subject location is ${stateOnly}; Jankar recommends a State-level authority unless the requested function is Central.`,confidence:'Medium',state:stateOnly,routeUrl:null,routeLabel:null};
  return {jurisdiction:'UNKNOWN',authority:'Authority not confidently determined',reason:'The request does not yet contain enough information to map the records to a public authority.',confidence:'Low',state:null,routeUrl:null,routeLabel:null};
}

function publicInfo(q,route){
  const t=q.toLowerCase();
  if(route.jurisdiction==='CENTRAL' && /railway/.test(t) && /(spend|spent|expenditure|budget|capital|capex|five year|last 5|last five)/.test(t)){
    return {
      found:true,
      headline:'Railway capital expenditure information is publicly available',
      answer:'Jankar found official Union Budget / Railway expenditure material relevant to capital outlay on Indian Railways. The figures below are presented with their budget-status labels because actual, revised and budget estimates should not be treated as identical categories.',
      points:['The information is held at Central Government level under the Ministry of Railways.','Official budget documents publish railway expenditure and capital-outlay figures.','For contractor-wise, station-wise or project-file-level details that are not published, an RTI may still be useful.'],
      data:RAIL_DEMO,
      dataLabel:'Official budget-series demo — values retain Actual/Revised/Budget labels',
      sources:[VERIFIED_SOURCES.indiaBudget,VERIFIED_SOURCES.rail]
    };
  }
  return {found:false,headline:'We found the responsible government route, but not enough verified public information to fully answer this request.',answer:'Jankar will not fill the gap with news, blogs or model memory. You can refine the question, follow the verified State/Central route, or prepare an RTI if you need records that are not publicly available.',points:[],data:null,sources:route.jurisdiction==='STATE'&&route.state==='Arunachal Pradesh'?[VERIFIED_SOURCES.arunachal,VERIFIED_SOURCES.arunachalRTI]:route.jurisdiction==='STATE'&&route.state==='Maharashtra'?[VERIFIED_SOURCES.mahaRTI]:[VERIFIED_SOURCES.centralRTI]};
}

function sourceList(list){return `<div class="sources-block"><h4>Verified government sources</h4>${list.map(x=>`<a class="source-row" target="_blank" rel="noopener" href="${e(x.url)}"><span><b>${e(x.title)}</b><small>${e(x.org)} · ${e(x.domain)}</small></span><span>↗</span></a>`).join('')}</div>`}

function landing(){return shell(`<main class="container"><section class="hero"><div><span class="pill">Citizen Information Platform</span><h1>What do you want to know?</h1><p>Tell Jankar in plain language. We first look for verified government information, figure out the responsible authority and only bring RTI into the journey when public information is not enough.</p><div class="search"><input id="hq" placeholder="e.g. Railway expenditure in the last four years"><button onclick="heroAsk()">Ask Jankar →</button></div><div class="chips"><button onclick="prefill('Railway capital expenditure in the last four years')">Railway expenditure</button><button onclick="prefill('Road project expenditure in Arunachal Pradesh')">Arunachal road projects</button><button onclick="prefill('Municipal road repairs in Pune')">Pune road repairs</button></div></div><div class="hero-visual"><div class="flow-card question">“I need government information.”</div><div class="flow-arrow">↓</div><div class="flow-grid"><div><b>1</b><span>Search verified public data</span></div><div><b>2</b><span>Find the right authority</span></div><div><b>3</b><span>RTI only if needed</span></div></div><div class="citizen-mark">?</div></div></section><section class="subtle-section"><div><b>Ask first, file later.</b><p>Jankar is designed around the citizen's question, not around government forms.</p></div><button class="outline" onclick="s.page='guide';render()">Know about RTI</button></section></main>`,'Ask Jankar')}
function prefill(q){document.getElementById('hq').value=q}
function heroAsk(){s.query=document.getElementById('hq').value.trim();if(s.query.length<5)return alert('Please describe what you want to know.');s.page='ask';s.result=null;render();setTimeout(()=>searchGov(true),50)}

function loginPage(){return shell(`<main class="login"><section class="panel"><div class="intro">${brand()}<h1>Login when you need your personal RTI workspace</h1><p>You can ask Jankar and discover public information without logging in. Login is required to save, submit-demo or track personal RTIs.</p><div class="warn">DEMO AUTHENTICATION — no SMS is sent.</div></div><div><h2>Login / Sign up</h2><label>Mobile number</label><input id="phone" value="+919876543210"><button onclick="sendOtp()">Send Demo OTP</button><div id="otpbox"></div><div id="err"></div></div></section></main>`)}
function sendOtp(){let p=document.getElementById('phone').value.replace(/ /g,'');if(!/^\+?\d{10,14}$/.test(p))return err('Enter a valid mobile number');document.getElementById('otpbox').innerHTML=`<div class="warn">Demo OTP: <b>246810</b></div><label>Enter OTP</label><input id="otp" maxlength="6"><button onclick="verify()">Verify & Continue</button>`}
function verify(){if(document.getElementById('otp').value!=='246810')return err('Invalid demo OTP');s.authed=true;s.user='Tasmayee';s.page=s.afterLogin||'dash';s.afterLogin=null;render()}
function err(t){document.getElementById('err').innerHTML=`<div class="bad">${e(t)}</div>`}

function dash(){return shell(`<main class="container"><div class="page-title"><div><h1>Welcome, Tasmayee 👋</h1><p>Continue your current question or review your RTIs.</p></div></div><div class="focus-card"><h2>What do you want to know today?</h2><div class="search"><input id="dq" placeholder="Ask Jankar in plain language"><button onclick="s.query=document.getElementById('dq').value;s.page='ask';s.result=null;render()">Ask Jankar →</button></div></div><div class="section-head"><h2>Your recent RTIs</h2><button class="link-btn" onclick="openMyRtis()">View all</button></div>${rtiMiniList()}<div class="trust-strip"><span>✓ Government sources only</span><span>✓ Nothing submitted automatically</span><span>✓ Subject location ≠ your current location</span></div></main>`)}
function rtiMiniList(){return `<div class="rti-mini">${SAMPLE_RTIS.slice(0,3).map(r=>`<article onclick="openRti('${r.id}')"><div><b>${e(r.title)}</b><small>${e(r.authority)}</small></div>${statusBadge(r.status)}</article>`).join('')}</div>`}

async function useLoc(){if(!navigator.geolocation)return alert('Location unavailable. Enter it manually.');navigator.geolocation.getCurrentPosition(async p=>{let txt='Location detected';try{let r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${p.coords.latitude}&lon=${p.coords.longitude}`,{headers:{'Accept-Language':'en'}});let d=await r.json(),a=d.address||{};txt=[a.city||a.town||a.village||a.county,a.state,a.country].filter(Boolean).join(', ')}catch{}s.userLoc=txt;let el=document.getElementById('uloc');if(el)el.value=txt},()=>alert('Location permission was not granted. You can enter it manually.'))}

function ask(){
  let out='';
  if(s.result){const r=s.result,route=r.route,info=r.info;
    const routeLink=route.routeUrl?`<a class="state-route" target="_blank" rel="noopener" href="${e(route.routeUrl)}">${e(route.routeLabel)} ↗</a>`:'';
    const actions=info.found?`<div class="action-panel"><h3>What would you like to do next?</h3><button onclick="downloadInfoPdf()">Save as PDF</button><button class="green" onclick="showInfoViz()">Visualise this data</button><button class="outline" onclick="askMore()">I need more information</button><button class="link-btn" onclick="focusAsk()">Ask a follow-up question</button></div>`:`<div class="action-panel"><h3>What would you like to do next?</h3>${routeLink}<button onclick="draftFromAsk()">Draft an RTI for the missing information</button><button class="outline" onclick="focusAsk()">Refine my question</button></div>`;
    out=`<section class="result"><div class="result-top"><div><span class="tag ${route.jurisdiction.toLowerCase()}">${route.jurisdiction}</span><h2>${info.found?'What we found':'What’s missing'}</h2></div><span class="confidence">Routing confidence: ${route.confidence}</span></div><div class="answer-block"><h3>${e(info.headline)}</h3><p>${e(info.answer)}</p>${info.points.length?`<ul>${info.points.map(p=>`<li>${e(p)}</li>`).join('')}</ul>`:''}${info.data?dataTable(info.data):''}</div><div class="why"><b>Why this authority?</b><p>${e(route.reason)}</p><strong>${e(route.authority)}</strong>${route.state?`<small>Subject location: ${e(route.state)}</small>`:''}</div>${sourceList(info.sources)}${actions}<div id="vizSlot"></div></section>`;
  }
  return shell(`<main class="container"><div class="page-title"><div><h1>Ask Jankar</h1><p>Tell us what you want to know; Jankar figures out the government machinery.</p></div></div><div class="ask-layout"><aside class="journey"><b>Your journey</b><span class="done">1. Ask your question</span><span class="${s.result?'done':''}">2. What we found</span><span class="${s.result?'done':''}">3. Why this authority?</span><span>4. RTI only if needed</span></aside><section class="cardbox"><label>Your question</label><textarea id="aq">${e(s.query)}</textarea><div class="loc-note">Jankar will first detect the <b>subject location from your question</b>. Your current location is optional and never decides jurisdiction on its own.</div><div class="locgrid"><div><label>Current location (optional)</label><input id="uloc" value="${e(s.userLoc)}"><button class="outline small" onclick="useLoc()">Use my location</button></div><div><label>Detected RTI subject location</label><input id="sloc" value="${e(s.subjectLoc)}" placeholder="Detected from your question; editable"></div></div><button onclick="searchGov()">Search verified government sources</button>${out}</section></div></main>`,'Ask Jankar')
}
function focusAsk(){document.getElementById('aq')?.focus()}
function searchGov(auto=false){s.query=document.getElementById('aq')?.value.trim()||s.query;if(s.query.length<5)return alert('Please describe the information you need.');const detected=extractSubjectLocation(s.query);const manual=document.getElementById('sloc')?.value.trim();s.subjectLoc=detected||manual||s.subjectLoc;s.userLoc=document.getElementById('uloc')?.value.trim()||s.userLoc;const route=routeQuery(s.query,s.subjectLoc);const info=publicInfo(s.query,route);s.result={route,info};s.authority=route.authority;s.jurisdiction=route.jurisdiction;render()}
function dataTable(data){return `<div class="data-table"><div class="data-head"><b>Year / period</b><b>₹ crore</b><b>Series type</b></div>${data.map(x=>`<div><span>${e(x.year)}</span><strong>${Number(x.value).toLocaleString('en-IN')}</strong><small>${e(x.label)}</small></div>`).join('')}</div>`}
function showInfoViz(){const slot=document.getElementById('vizSlot');if(!slot||!s.result?.info?.data)return;slot.innerHTML=`<div class="viz-card"><h3>Visualisation</h3>${bars(s.result.info.data)}<p class="caption">The series includes Actual/Revised/Budget-labelled values. Jankar preserves the status label instead of silently treating them as equivalent actuals.</p></div>`;slot.scrollIntoView({behavior:'smooth'})}
function downloadInfoPdf(){
  const info=s.result?.info,route=s.result?.route;if(!info)return;
  const w=window.open('','_blank');const rows=info.data?`<table><tr><th>Period</th><th>₹ crore</th><th>Series type</th></tr>${info.data.map(x=>`<tr><td>${e(x.year)}</td><td>${Number(x.value).toLocaleString('en-IN')}</td><td>${e(x.label)}</td></tr>`).join('')}</table>`:'';
  w.document.write(`<html><head><title>Jankar India — Information Report</title><style>body{font-family:Arial;padding:36px;color:#123}h1{color:#0D2B5C}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccd;padding:8px;text-align:left}.note{background:#f5f7fa;padding:12px}</style></head><body><h1>Jankar India</h1><h2>${e(s.query)}</h2><p>${e(info.answer)}</p>${rows}<h3>Authority</h3><p>${e(route.authority)} — ${e(route.jurisdiction)}</p><h3>Verified government sources</h3>${info.sources.map(x=>`<p>${e(x.title)} — ${e(x.url)}</p>`).join('')}<p class="note">Generated by Jankar India from the information displayed in this session. Use your browser's Print → Save as PDF option.</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();
}
function askMore(){s.needMore=true;draftFromAsk()}
function draftFromAsk(){if(!s.result)return;const route=s.result.route;if(route.jurisdiction==='UNKNOWN')return alert('Jankar needs a more specific subject before it can identify the responsible authority. Please refine your question.');if(!s.authed){s.afterLogin='review';prepareDraft();return login()}prepareDraft();s.page='review';render()}
function prepareDraft(){const route=s.result.route;s.authority=route.authority;s.jurisdiction=route.jurisdiction;s.draft=`To,\nThe Public Information Officer,\n${s.authority}\n\nSubject: Request for information under the Right to Information Act, 2005\n\nSir/Madam,\n\nKindly provide the following information/records under the Right to Information Act, 2005:\n\n1. Please provide the records/information corresponding to the following subject: ${s.query}\n2. Please provide the information for the period relevant to the request, including year-wise details where such records are maintained.\n3. Please provide copies/extracts of the relevant records pertaining to ${s.subjectLoc||'the applicable jurisdiction'}, where applicable.\n4. Where the information is maintained electronically, kindly provide it in electronic form where permissible.\n\nApplicant Details:\nName: Tasmayee\nAddress: [To be completed by applicant]\nEmail: [To be completed by applicant]\nMobile: [Registered mobile]\n\nDate: [Date of submission]`;}

function manual(){if(!s.authed)return requireLogin('manual')||'';return shell(`<main class="container"><div class="page-title"><div><h1>File RTI manually</h1><p>Write your request yourself. Jankar can optionally improve clarity without changing your meaning.</p></div></div><div class="two"><section class="cardbox"><label>Jurisdiction</label><select id="mj"><option>CENTRAL</option><option>STATE</option><option>LOCAL</option></select><label>Public Authority</label><input id="ma" placeholder="Public authority"><label>Information requested</label><textarea id="mt" placeholder="Describe the records/information you need"></textarea><label>Subject location</label><input id="ml" placeholder="State / district if relevant"><button onclick="manualDraft()">Improve structure with Jankar</button></section><aside class="cardbox"><h3>Before you continue</h3><p>Ask for existing records, be specific about the period/location and review the final application before proceeding.</p><div class="good">Nothing is submitted automatically.</div></aside></div></main>`,'')}
function manualDraft(){let q=document.getElementById('mt').value.trim(),a=document.getElementById('ma').value.trim();if(!q||!a)return alert('Enter authority and request text.');s.query=q;s.subjectLoc=document.getElementById('ml').value;s.authority=a;s.jurisdiction=document.getElementById('mj').value;s.draft=`To,\nThe Public Information Officer,\n${a}\n\nSubject: Request for information under the Right to Information Act, 2005\n\nSir/Madam,\n\nKindly provide the following information/records under the Right to Information Act, 2005:\n\n${q}\n\nThe requested records relate to ${s.subjectLoc||'the applicable jurisdiction'}, where relevant. Where the information is maintained electronically, kindly provide it in electronic form where permissible.\n\nApplicant Details:\nName: Tasmayee\nAddress: [To be completed by applicant]\nEmail: [To be completed by applicant]\nMobile: [Registered mobile]\n\nDate: [Date of submission]`;s.page='review';render()}
function review(){if(!s.draft&&s.result)prepareDraft();return shell(`<main class="container"><div class="page-title"><div><h1>Review your RTI request</h1><p>Jankar prepared the structure. The application below contains only the request text — no AI notices are inserted into the RTI itself.</p></div></div><div class="two"><section class="cardbox"><div class="notice-soft">Jankar helped structure this request. Review every line before continuing.</div><textarea id="draft" class="draftarea">${e(s.draft)}</textarea><label class="check"><input id="approve" type="checkbox"> I have reviewed the draft and confirm it reflects my request.</label><button onclick="submitDemo()">Approve & Record Demo Submission</button></section><aside class="cardbox"><b>Recommended authority</b><p>${e(s.authority)}</p><b>Jurisdiction</b><p>${e(s.jurisdiction)}</p><div class="good"><b>Nothing is submitted automatically.</b><p>This hackathon build records a demo submission only; it is not connected to a government filing API.</p></div></aside></div></main>`,'')}
function submitDemo(){if(!document.getElementById('approve').checked)return alert('Explicit citizen approval is required.');s.draft=document.getElementById('draft').value;s.submission={id:`JNK/2026/${String(Date.now()%1000000).padStart(6,'0')}`,timeline:['Draft prepared','Citizen reviewed and approved','Demo submission recorded'],title:s.query,authority:s.authority,status:'SUBMITTED_DEMO'};s.page='track';render()}

function statusBadge(st){const names={RESPONSE_RECEIVED:'Response received',UNDER_PROCESS:'Under processing',TRANSFERRED:'Transferred',PARTIALLY_ANSWERED:'Partially answered',ADDITIONAL_INFO_REQUESTED:'Action required',APPEAL_AVAILABLE:'Appeal available',SUBMITTED_DEMO:'Demo submitted'};return `<span class="status ${st.toLowerCase()}">${names[st]||e(st)}</span>`}
function track(){if(!s.authed)return requireLogin('track')||'';const all=s.submission?[{id:s.submission.id,title:s.submission.title,authority:s.submission.authority,jurisdiction:s.jurisdiction,status:'SUBMITTED_DEMO',date:'Today',hasDocument:false},...SAMPLE_RTIS]:SAMPLE_RTIS;return shell(`<main class="container"><div class="page-title"><div><h1>My RTIs</h1><p>See what is happening with each request and open responses when documents are available.</p></div><button class="outline" onclick="s.page='manual';render()">File manually</button></div><div class="rti-list">${all.map(r=>`<article class="rti-row"><div class="rti-main"><b>${e(r.title)}</b><small>${e(r.id)} · ${e(r.authority)} · ${e(r.date)}</small></div>${statusBadge(r.status)}<div class="rti-actions">${r.hasDocument?`<button onclick="openRti('${r.id}')">View response</button>`:`<button class="outline" onclick="openRti('${r.id}')">View details</button>`}</div></article>`).join('')}</div></main>`,'My RTIs')}
function openRti(id){if(!s.authed)return requireLogin('track');const r=SAMPLE_RTIS.find(x=>x.id===id)||(s.submission?.id===id?{id,title:s.submission.title,authority:s.submission.authority,jurisdiction:s.jurisdiction,status:'SUBMITTED_DEMO',date:'Today',hasDocument:false}:null);if(!r)return;s.selectedRti=r;s.page=r.hasDocument?'document':'rtiDetail';render()}
function rtiDetail(){const r=s.selectedRti;return shell(`<main class="container"><button class="back" onclick="s.page='track';render()">← My RTIs</button><div class="page-title"><div><h1>${e(r.title)}</h1><p>${e(r.id)}</p></div>${statusBadge(r.status)}</div><div class="two"><section class="cardbox"><h3>Status timeline</h3><div class="timeline">✓ Request recorded</div><div class="timeline">✓ Sent to selected authority in demo workflow</div><div class="timeline">● ${e(r.status.replaceAll('_',' '))}</div></section><aside class="cardbox"><b>Authority</b><p>${e(r.authority)}</p><b>Jurisdiction</b><p>${e(r.jurisdiction)}</p></aside></div></main>`,'My RTIs')}

const DOC_DATA={
 response:{title:'Synthetic RTI Response — Railway redevelopment expenditure',summary:'The response provides year-wise expenditure records for four periods and refers to attached expenditure statements. One requested period is not present in the supplied extract.',missing:'The requested 2025-26 figure is not present in the demo response.',answered:'2021-22 to 2024-25 expenditure figures are provided.',data:RAIL_DEMO,body:`Office of the Public Information Officer\nMinistry of Railways\n\nSubject: Reply to RTI application regarding railway redevelopment expenditure\n\nWith reference to the RTI application, available year-wise capital expenditure records are enclosed for 2021-22, 2022-23, 2023-24 and 2024-25. The enclosed figures correspond to the categories stated in the relevant budget documents. Information for 2025-26 is not contained in the enclosed statement.\n\nThis is SYNTHETIC DEMONSTRATION CONTENT created for the Jankar India hackathon prototype.`},
 partial:{title:'Synthetic RTI Response — Partial information supplied',summary:'The response answers part of the request but does not contain all requested project-level records.',missing:'Project-wise breakup and one requested period are absent.',answered:'Aggregate expenditure and department-level information are present.',data:[{year:'2022-23',value:42},{year:'2023-24',value:58},{year:'2024-25',value:63}],body:`Public Information Officer\nState Public Authority\n\nThe available aggregate expenditure is provided in the attached statement. Project-wise breakup could not be located in the enclosed response.\n\nThis is SYNTHETIC DEMONSTRATION CONTENT.`}
};
function documentPage(){const r=s.selectedRti,d=DOC_DATA[r.docType]||DOC_DATA.response;return shell(`<main class="container"><button class="back" onclick="s.page='track';render()">← My RTIs</button><div class="page-title"><div><h1>Understand your RTI response</h1><p>${e(r.title)}</p></div>${statusBadge(r.status)}</div><div class="document-layout"><section class="doc-view"><div class="doc-paper"><span class="pill">SYNTHETIC RESPONSE DOCUMENT</span><pre>${e(d.body)}</pre></div></section><aside class="doc-assistant"><h2>Did you actually get your answer?</h2><p>Jankar can work with this response document and help you understand it.</p><div class="doc-actions"><button onclick="docAction('summary')">Summarise simply</button><button onclick="docAction('missing')">Check what’s missing</button><button onclick="docAction('visualise')">Visualise the data</button></div><label>Ask a question about this document</label><div class="inline-input"><input id="docq" placeholder="e.g. What was provided for 2023-24?"><button onclick="docAsk()">Ask</button></div><div class="upload-box"><b>Have another RTI response?</b><p>Upload a PDF to start the document-understanding flow.</p><input id="pdfUpload" type="file" accept="application/pdf" onchange="handlePdfUpload(event)"></div><div id="docResult"></div></aside></div></main>`,'My RTIs')}
function docAction(type){const d=DOC_DATA[s.selectedRti.docType]||DOC_DATA.response,el=document.getElementById('docResult');if(type==='summary')el.innerHTML=`<div class="assistant-answer"><h3>Simple summary</h3><p>${e(d.summary)}</p></div>`;if(type==='missing')el.innerHTML=`<div class="assistant-answer warn"><h3>What’s missing?</h3><p>${e(d.missing)}</p><button onclick="s.page='appeal';render()">Review next step</button></div>`;if(type==='visualise')el.innerHTML=`<div class="assistant-answer"><h3>Response data</h3>${bars(d.data)}<small>Visualised only because you asked Jankar to visualise this response.</small></div>`}
function docAsk(){const q=(document.getElementById('docq').value||'').toLowerCase(),d=DOC_DATA[s.selectedRti.docType]||DOC_DATA.response;let ans='I can only answer from the response document available in this demo.';if(/2023|2023-24/.test(q)){const x=d.data.find(x=>x.year==='2023-24');ans=x?`The response contains ${x.value.toLocaleString('en-IN')} in the demo dataset for 2023-24. Check the series label/context before comparing it with other periods.`:'The document does not contain a 2023-24 value.'}else if(/missing|not answer|unanswered/.test(q))ans=d.missing;else if(/summary|summar/.test(q))ans=d.summary;else if(/what.*provided|answer/.test(q))ans=d.answered;document.getElementById('docResult').innerHTML=`<div class="assistant-answer"><h3>Jankar</h3><p>${e(ans)}</p><small>Answer grounded only in the selected synthetic response document.</small></div>`}
function handlePdfUpload(ev){const f=ev.target.files?.[0];if(!f)return;document.getElementById('docResult').innerHTML=`<div class="assistant-answer"><h3>${e(f.name)} uploaded</h3><p>This public zero-cost demo shows the document-agent interaction using the synthetic response content. The production/local architecture uses PDF extraction + local RAG before answering.</p><div class="doc-actions"><button onclick="docAction('summary')">Summary</button><button onclick="docAction('visualise')">Visualise</button></div></div>`}

function bars(data){let mx=Math.max(...data.map(x=>x.value));return `<div class="chart">${data.map(x=>`<div class="bar-col"><b>${Number(x.value).toLocaleString('en-IN')}</b><i style="height:${Math.max(25,x.value/mx*170)}px"></i><small>${e(x.year)}</small></div>`).join('')}</div>`}
function appeal(){const d=s.selectedRti?DOC_DATA[s.selectedRti.docType]||DOC_DATA.response:DOC_DATA.response;return shell(`<main class="container"><div class="page-title"><div><h1>Review the next step</h1><p>Jankar highlights gaps without making a legal determination.</p></div></div><div class="two"><section class="cardbox"><div class="warn"><b>Potentially missing information</b><p>${e(d.missing)}</p></div><button onclick="generateAppeal()">Prepare a review / First Appeal draft</button><pre id="ap"></pre></section><aside class="cardbox"><h3>Guardrails</h3><p>This is assistance, not a legal finding. Nothing is submitted automatically.</p></aside></div></main>`,'My RTIs')}
function generateAppeal(){document.getElementById('ap').textContent=`Draft for citizen review\n\nSubject: Request for review / First Appeal regarding incomplete information\n\nThe response received appears not to address all information requested in the original application. In particular, the following item may require review:\n\n${(DOC_DATA[s.selectedRti?.docType]||DOC_DATA.response).missing}\n\nI request that the available records relating to the unanswered portion be reviewed and provided as applicable.\n\nCitizen must verify this draft before any real filing.`}

function guide(){return shell(`<main class="container"><div class="page-title"><div><h1>Know about RTI</h1><p>Understand the Right to Information in simple language and how Jankar fits into the journey.</p></div></div><div class="guide-grid"><article><span>01</span><h3>What is RTI?</h3><p>The Right to Information Act, 2005 gives citizens a legal framework to request information held by public authorities, subject to the Act and applicable exemptions.</p></article><article><span>02</span><h3>Why was it introduced?</h3><p>RTI supports transparency and accountability by enabling citizens to seek access to government-held information and records.</p></article><article><span>03</span><h3>Do I always need to file?</h3><p>No. A large amount of government information is already published. Jankar searches verified public information first so you do not file an RTI unnecessarily.</p></article><article><span>04</span><h3>How does Jankar help?</h3><p>Ask in plain language → find public information → identify Central/State/Local authority → prepare RTI only for the remaining gap → help understand the response.</p></article></div><div class="golden-flow"><b>The Jankar principle</b><span>Question</span>→<span>Public information</span>→<span>Gap</span>→<span>Authority</span>→<span>RTI if needed</span>→<span>Understand response</span></div>${sourceList([VERIFIED_SOURCES.centralRTI])}</main>`,'Know About RTI')}
function profile(){return shell(`<main class="container"><div class="page-title"><div><h1>Profile</h1><p>Demo citizen profile</p></div></div><section class="cardbox profile-card"><div class="avatar big">T</div><div><h2>Tasmayee</h2><p>Demo account • +91 98765 43210</p><button class="outline" onclick="logout()">Logout</button></div></section></main>`)}

function render(){let f={landing,login:loginPage,dash,ask,manual,review,track,rtiDetail,document:documentPage,appeal,guide,profile}[s.page]||landing;app.innerHTML=f()}
render();
